sonar.projectKey=CesarHerr_MoneyConverter
sonar.organization=cesarherr
sonar.host.url=https://sonarcloud.io

sonar.sources=app,lib
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**,node_modules/**,db/schema.rb,db/migrate/**
sonar.ruby.rubocop.reportPaths=tmp/rubocop.json

sonar.language=ruby
sonar.sources=app
sonar.tests=spec
sonar.ruby.coverage.reportPaths=coverage/coverage.xml
