name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Setup DB
        run: |
          RAILS_ENV=test bin/rails db:create db:schema:load

      - name: Run RSpec with coverage
        run: bundle exec rspec
        env:
          RAILS_ENV: test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=TU_ORGANIZACION
            -Dsonar.projectKey=TU_PROYECTO
            -Dsonar.ruby.coverage.reportPaths=coverage/coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
